/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 ../../public/spanish_arch.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Sparch(props) {
  const { nodes, materials } = useGLTF('/spanish_arch.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['default'].geometry} material={materials['Material.001']}  rotation={[-1.57,0,1.1]} position={[-1136,4.36,1302]} scale={[0.4,0.4,0.4]}/>
    </group>
  )
}

useGLTF.preload('/spanish_arch.glb')
